app.directive('appDefaultView', function () {

    var template = [
    '<md-card>',
        '<md-card-header>',
            '<md-card-header-text>',
                '<span class="md-title">{{ elements()[0].name }}</span>',
                '<span class="md-subhead">{{ item.type == \'rent\' ? \'Alquiler\' : \'Venta\' }}</span>',
            '</md-card-header-text>',
        '</md-card-header>',
        '<img ng-src="{{ elements()[0].image_path }}" class="md-card-image">',
        '<md-card-title>',
            '<md-card-title-text>',
                '<span class="md-headline" ng-if="elements()[0].contact_phone != null">{{ translate("general.", \'telefono\') | capitalize }}: {{ elements()[0].contact_phone }}</span>',
                '<span class="md-subhead" ng-if="elements()[0].energy_cert != null">{{ translate("general.", \'energy_cert\') | capitalize }}: {{ elements()[0].energy_cert | capitalize }}</span>',
                //'<span class="md-headline" ng-if="elements()[0].price != null">{{ elements()[0].price }} €</span>',
                //'<span class="md-subhead" ng-if="elements()[0].address != null">{{ elements()[0].address }}</span>',
            '</md-card-title-text>',
        '</md-card-title>',
        //'<md-card-actions layout="row" layout-wrap layout-align="start center">',
        //        '<p class="md-subhead" flex="100" ng-if="elements()[0].contact_phone != null">{{ translate("general.", \'telefono\') | capitalize }}: {{ elements()[0].contact_phone }}</p>',
        //        '<p class="md-subhead" flex="100" ng-if="elements()[0].energy_cert != null">{{ translate("general.", \'energy_cert\') | capitalize }}: {{ elements()[0].energy_cert | capitalize }}</p>',
        //'</md-card-actions>',
        '<md-card-content>',
            '<div flex="100" ng-if="elements()[0].description != null">',
               '<h2 class="md-headline">Descripción</h2>',
                '<md-content bind-html-compile="elements()[0].description"></md-content>',
            '</div>',
            '<div flex="100" ng-if="elements()[0].observations != null">',
               '<h2 class="md-headline">Observaciones</h2>',
                '<md-content bind-html-compile="elements()[0].observations"></md-content>',
            '</div>',
            '<div flex="100" layout="row" layout-wrap>',
               '<h2 flex="100" class="md-headline">Datos</h2>',
               '<md-list-item ng-if="elements()[0][item] !== 0 && elements()[0][item] != null" class="md-2-line" flex-gt-md="50" flex="100" ng-repeat="item in [ \'m2_terrain\', \'building_status\', \'m2_built\', \'building_floors\', \'m2_balcony\', \'pool\', \'year\', \'stairs\', \'bedrooms\', \'elevator\', \'restroom\', \'storage\', \'kitchen\', \'parking\', \'livingroom\', \'furniture\', \'ibi\', \'views\', \'community\', \'telephone\', \'wifi\' ]" ng-click="null" ng-if="elements()[0][item] != null">',
                   '<div ng-if="elements()[0][item] === true || elements()[0][item] === false" class="md-list-item-text" layout="column">',
                       '<h3>{{ translate("general.", item) | capitalize }}</h3>',
                       '<h4>{{ translate("general.", elements()[0][item] === true ? \'si\' : \'no\') | capitalize }}</h4>',
                   '</div>',
                   '<div ng-if="elements()[0][item] !== true && elements()[0][item] !== false" class="md-list-item-text" layout="column">',
                       '<h3>{{ translate("general.", item) | capitalize }}</h3>',
                       '<h4>{{ elements()[0][item] }}</h4>',
                   '</div>',
               '</md-list-item>',
            '</div>',
            '<div flex="100" ng-if="elements()[0].availible != true">',
               '<md-list-item md-colors="::{background: \'default-warn-500\'}" flex="100" ng-click="null">',
                   '<div class="md-list-item-text" layout="row" flex="100" layout-align="center center">',
                       '<h1>{{ elements()[0].type == \'sell\' ? \'Vendido\' : \'Alquilado\' }}</h1>',
                   '</div>',
               '</md-list-item>',
            '</div>',
            '<div flex="100" ng-if="elements()[0].price != null">',
               '<md-list-item md-colors="::{background: \'default-primary-500\'}" flex="100" ng-click="null">',
                   '<div class="md-list-item-text" layout="row" flex="100" layout-align="center center">',
                       '<h1>{{ elements()[0].price }} €</h1>',
                   '</div>',
               '</md-list-item>',
            '</div>',
            '<div flex="100" ng-if="elements()[0].map_iframe != null">',
               '<h2 class="md-headline">Mapa</h2>',
                '<md-content bind-html-compile="elements()[0].map_iframe" class="flex-video"></md-content>',
            '</div>',
            '<div flex="100" ng-if="elements()[0].image_paths != null">',
               '<h2 class="md-headline">Galería de imágenes</h2>',
               '<slick adaptiveHeight="true" infinite="true" dots="false" arrows="true" data="elements()[0].image_paths" init-onload="true" autoplay="true">',
                   '<div layout="row" ng-repeat="image_path in elements()[0].image_paths">',
                        '<a ng-href="{{ image_path }}" target="_blank" flex="100" layout="row"><div class="territorial-header" flex="100" style="background-image: url(\'{{ image_path }}\');"></div></a>',
                   '</div>',
               '</slick>',
            '</div>',
        '</md-card-content>',
    '</md-card>'
    ].join(' ');

    return {
        restrict: 'E',
        scope: false,
        template: template
    };
});


